config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      post :downgrade
    end
  end
  
  resources :categories do
    resources :posts, except: [:index] 
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post '/like' => 'likes#like', as: :like
    post '/unlike' => 'likes#unlike', as: :unlike
  end

  get 'home/faq'
  get 'home/contact'
  root 'home#about'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like
    if user_signed_in?
      @post = Post.find(params[:post_id])
      if @post.like == nil || @post.like == 0
        @post.like = 1
      else
        @post.like = @post.like + 1
      end
      
      @like = Like.new
      @like.post_id = @post.id
      @like.user = current_user
      
      @like.save
      @post.save
    end
    redirect_to :back
  end
  
  def unlike
    if user_signed_in?
      @post = Post.find(params[:post_id])
      if @post.like != nil || @post.like > 0
        @post.like = @post.like - 1
      end
      
      @like = Like.where(post_id: params[:post_id], user: current_user)
      if @like.count > 0
        @like.destroy_all
        @post.save
      end
    end
    redirect_to :back
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user %>
  <div class="like pull-left">
    <% if is_voted?(post) %>
      <div class="voted"><small><%= post.like %></small></div>
      <div class="voted"><%= link_to "", post_unlike_path(post), class: 'glyphicon glyphicon-thumbs-up', method: :post %></div>
    <% else %>
      <div class="not-voted"><small><%= post.like %></small></div>
      <div class="not-voted"><%= link_to "", post_like_path(post), class: 'glyphicon glyphicon-thumbs-up', method: :post %></div>
    <% end %>
  </div>
<% else %>
  <div class="like pull-left" onclick="alert('Please login')">
    <div class="not-voted"><small><%= post.like %></small></div>
    <div class="not-voted"><i class="glyphicon glyphicon-thumbs-up"></i></div>
  </div>
<% end %>