config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      post :downgrade
    end
  end
  
  resources :categories do
    resources :posts, except: [:index] 
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post '/like' => 'likes#like', as: :like
    post '/unlike' => 'likes#unlike', as: :unlike
  end

  get 'home/faq'
  get 'home/contact'
  root 'home#about'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  default_scope -> { order(updated_at: :desc, created_at: :desc) }
  
  before_save { self.like ||= 0 }
  
  validates :body, presence: { message: 'Post body cannot be emptied.' }, length: { maximum: 350, message: 'Post body is limited to 350 characters.' }
  validates :category, presence: { message: 'A Post must have associated category.' }
  validates :user, presence: { message: 'A Post must have associated user.' }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @post = Post.new
  end

  def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.build(post_params)
    
    if !current_user
      flash[:alert] = "You must register to create new post."
      redirect_to [@category]
    else
      @post.user = current_user
      if @post.save
        flash[:notice] = "Post was created successfully."
        redirect_to [@category, @post]
      else
        flash.now[:alert] = error_messages(@post)
        render :new
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    
    if !current_user
      flash[:alert] = "You must register to edit post."
      redirect_to [@post.category, @post]
    else
      if !(current_user.id == @post.user_id || current_user.admin?)
        flash[:alert] = "You must be the owner of the post in order to edit."
        redirect_to [@post.category, @post]
      else
        if @post.save
          flash[:notice] = "Post was updated successfully."
          redirect_to [@post.category, @post]
        else
          flash.now[:alert] = error_messages(@post)
          render :edit
        end
      end
    end
  end
  
  def destroy
    @post = Post.find(params[:id])

    if !current_user
      flash[:alert] = "You must register to delete a post."
      redirect_to [@post.category, @post]
    else
      if !(current_user.id == @post.user_id || current_user.admin?)
        flash[:alert] = "You must be the owner of the post in order to delete."
        redirect_to [@post.category, @post]
      else
        if @post.destroy
          flash[:notice] = "Post was deleted successfully."
          redirect_to @post.category
        else
          flash.now[:alert] = "There was an error deleting the post."
          render :show
        end
      end
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_owned_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/views/posts/_form.html.erb
<%= form_for [category, post] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Cancel", call_back, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>Edit Post</h3>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { category: @post.category, post: @post, call_back: category_post_path(@post.category, @post) } %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-2">
  </div>
  <div class="col-md-6 top">
  </div>
  <div class="col-md-2">
  </div>
  <div class="col-md-1">
  </div>
</div>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-2">
    <div class="left short">
      <p><h4>Guidelines for new posts</h4></p>
      <ul>
        <li>Make sure it rhymes.</li>
        <li>Don't use the letter "A".</li>
        <li>The incessant use of hashtags will get you banned.</li>
      </ul>
    </div>
  </div>
  <div class="col-md-6">
    <div class="mid short">
      <div>
        <%= render partial: 'form', locals: { category: @category, post: @post, call_back: category_path(@category) } %>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="left short">
    </div>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-1 one">
  </div>
  <div class="col-md-2 two">
  </div>
  <div class="col-md-6 six top">
    <% case @post.category.id %>
      <% when 1 %>
        <%= image_tag("main/rushmore.png", :alt => "travel", size: "728x90") %>
      <% when 2 %>
        <%= image_tag("main/brazil.png", :alt => "travel", size: "728x90") %>
      <% when 3 %>
        <%= image_tag("main/beach.png", :alt => "travel", size: "728x90") %>
      <% when 4 %>
        <%= image_tag("main/hike.png", :alt => "travel", size: "728x90") %>
      <% else %>
      no pic
    <% end %>
  </div>
  <div class="col-md-2 two">
  </div>
  <div class="col-md-1 one">
  </div>
</div>
<div class="row">
  <div class="col-md-1 one">
  </div>
  <div class="col-md-2 two">
    <div class="left short middiv">
      <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=webboard05-20&marketplace=amazon&region=US&placement=B072MP2PVV&asins=B072MP2PVV&linkId=d750afa5190ea05e847fbfdcd171c642&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
      </iframe>
      <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=webboard05-20&marketplace=amazon&region=US&placement=B01LYZNM7V&asins=B01LYZNM7V&linkId=ed1f111c6292f16e762b0a0719ddf2fa&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
      </iframe>
      <a target="_blank"  href="https://www.amazon.com/gp/offer-listing/B01L6RE7Z4/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01L6RE7Z4&linkCode=am2&tag=webboard05-20&linkId=b24118964eb10c866d46eb9e32f05dc5"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B01L6RE7Z4&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=webboard05-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=webboard05-20&l=am2&o=1&a=B01L6RE7Z4" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
    </div>
  </div>
  <div class="col-md-6 six">
    <div class="mid">
      <div class="post-header">
        <%= render partial: 'likes/like', locals: { post: @post } %>
        <%= @post.body %>
      </div>
      <div class="comment-padding">
        <u>Comments</u>
        <% @post.comments.each do |c| %>
          <%= render partial: 'comments/comment', locals: {comment: c} %>
        <% end %>
        <% if current_user %>
          <%= render 'comments/form', comment: Comment.new, post: @post %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-2 two">
    <div class="right short middiv">
      <% if user_owned_post?(@post) %>
        <br />
        <%= link_to "Edit Post", edit_category_post_path(@post.category, @post), class: 'btn btn-primary' %>
        <%= link_to "Delete Post", [@post.category, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'All related comments will also be deleted. Are you sure you want to delete this post?' } %>
      <% end %>
      <br />
      <%= link_to "Back to Category", category_path(@post.category), class: 'btn btn-default' %>
      <div class="middiv">
        <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=14&l=ur1&category=sports&banner=0022YXJ8ZK2V14C43PG2&f=ifr&linkID=f00f09b07a708d9e468b726ce8648f46&t=webboard05-20&tracking_id=webboard05-20" width="160" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
      </div>    
    </div>
   </div>
  <div class="col-md-1 one">
  </div>
</div>