config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      post :downgrade
    end
  end
  
  resources :categories do
    resources :posts, except: [:index] 
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post '/like' => 'likes#like', as: :like
    post '/unlike' => 'likes#unlike', as: :unlike
  end

  get 'home/faq'
  get 'home/contact'
  root 'home#about'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy
 
  validates :name, presence: { message: 'Category name cannot be emptied.' }
  validates :description, presence: { message: 'Category description cannot be emptied.' }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include ApplicationHelper
  
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @posts_page = @category.posts.page(params[:page]).per(8)
  end
  
  def new
    @category = Category.new
  end  
  
  def create
    @category = Category.new(cat_params)

    if !is_admin?
      flash[:alert] = "Only admin can create category."
      redirect_to @category
    else      
      if @category.save
        redirect_to @category, notice: "Category was saved successfully."
      else
        flash.now[:alert] = error_messages(@category)
        render :new
      end
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    @category.assign_attributes(cat_params)
    
    if !is_admin?
      flash[:alert] = "Only admin can edit category."
      redirect_to @category
    else      
      if @category.save
        flash[:notice] = "Category was updated successfully."
        redirect_to @category
      else
        flash.now[:alert] = error_messages(@category)
        render :edit
      end
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    
    if !is_admin?
      flash[:alert] = "Only admin can delete category."
      redirect_to @category
    else      
      if @category.destroy
        flash[:notice] = "\"#{@category.name}\" was deleted successfully."
        redirect_to action: :index
      else
        flash.now[:alert] = "There was an error deleting the category."
        render :show
      end
    end
  end
  
  private
  def cat_params
    params.require(:category).permit(:name, :description, :public)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter category name" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter category description" %>
  </div>
  <div class="form-group">
    <%= f.check_box :public %>
    <%= f.label :public_category %>   
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
  <%= link_to "Cancel", call_back, class: 'btn btn-default' %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for categories:</p>
    <ul>
      <li>Make sure the category is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { category: @category, call_back: category_path(@category) } %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-md-1 one">
  </div>
  <div class="col-md-2 two">
  </div>
  <div class="col-md-6 six top">
    <%= image_tag("main/usa.png", :alt => "travel", size: "728x90") %>
  </div>
  <div class="col-md-2 two">
  </div>
  <div class="col-md-1 one">
  </div> 
</div>
<div class="row">
  <div class="col-md-1 one">
  </div>
  <div class="col-md-2 two">
    <div class="left tall middiv">
      <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=webboard05-20&marketplace=amazon&region=US&placement=B00V7T1YRQ&asins=B00V7T1YRQ&linkId=5f701940c0ef1fdbd34c3fc244ddfb41&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
      </iframe>
      <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=webboard05-20&marketplace=amazon&region=US&placement=B01BY6UCDS&asins=B01BY6UCDS&linkId=ad1997e11fbe6a495cef1a5ff8a77cfd&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
      </iframe>
      <a target="_blank"  href="https://www.amazon.com/gp/offer-listing/B073P147DM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B073P147DM&linkCode=am2&tag=webboard05-20&linkId=26b155f8eb139045acb16703b0cd7012"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B073P147DM&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=webboard05-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=webboard05-20&l=am2&o=1&a=B073P147DM" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
    </div>
  </div>
  <div class="col-md-6 six">
    <div class="mid tall">
      <% @categories.each do |category| %>
        <div>
          <div class="cat-header">
            <%= link_to category.name, category %>&nbsp;&nbsp;
            <%= category.description %>
            <div class="pull-right">
              <%= pluralize(category.posts.count, "post") %>
            </div>
          </div>
          <% category.posts.first(5).each do |p| %>
          <div class='cat-post'>
            <%= (p.body.html_safe).truncate(150) %>
            <small>
              <div class="like-info"><%= p.like %>&nbsp;&nbsp;<span class="glyphicon glyphicon-thumbs-up"></span></div>
              <div class="post-info"><%= time_ago_in_words(p.created_at) %> ago by <span class="email"><%= p.user.email.truncate(25) %></span></div>
            </small>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-2 two">
    <div class="right tall middiv">
      <% if is_admin? %>
        <%= link_to "Add New Category", new_category_path, class: 'btn btn-primary' %><br /><br />
      <% end %>
      <div class="middiv">
        <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=14&l=ur1&category=camera&banner=0X573SW5MCVBMYR6EN02&f=ifr&linkID=781ea01ce550df129fee11c6d5af3fe2&t=webboard05-20&tracking_id=webboard05-20" width="160" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
        <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=14&l=ur1&category=hotnewreleases&banner=1BWCMZYQA5F2PESPW182&f=ifr&linkID=9a252dff7b05abc84d6771de2af77bfe&t=webboard05-20&tracking_id=webboard05-20" width="160" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>      </div>
    </div>
  </div>
  <div class="col-md-1 one">
  </div>
</div>

app/views/categories/new.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-2">
  </div>
  <div class="col-md-6 top">
  </div>
  <div class="col-md-2">
  </div>
  <div class="col-md-1">
  </div>
</div>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-2">
    <div class="left short">
      <p><h4>Guidelines for new categories:</h4></p>
      <ul>
        <li>Make sure the category is appropriate.</li>
        <li>Never insult dogs.</li>
        <li>Smile when you type.</li>
      </ul>
    </div>
  </div>
  <div class="col-md-6">
    <div class="mid short">
      <div>
        <%= render partial: 'form', locals: { category: @category, call_back: categories_path } %>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="left short">
    </div>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-md-1 one">
  </div>
  <div class="col-md-2 two">
  </div>
  <div class="col-md-6 six top">
    <% case @category.id %>
      <% when 1 %>
        <%= image_tag("main/grandcanyon.png", :alt => "travel", size: "728x90") %>
      <% when 2 %>
        <%= image_tag("main/greece.png", :alt => "travel", size: "728x90") %>
      <% when 3 %>
        <%= image_tag("main/india.png", :alt => "travel", size: "728x90") %>
      <% when 4 %>
        <%= image_tag("main/bike.png", :alt => "travel", size: "728x90") %>
      <% else %>
      no pic
    <% end %>
  </div>
  <div class="col-md-2 two">
  </div>
  <div class="col-md-1 one">
  </div>
</div>
<div class="row">
  <div class="col-md-1 one">
  </div>
  <div class="col-md-2 two">
    <div class="left short middiv">
      <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=webboard05-20&marketplace=amazon&region=US&placement=B01LJS65NC&asins=B01LJS65NC&linkId=403818d85d47bafa8b6ec02701693b30&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
      </iframe>
      <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=webboard05-20&marketplace=amazon&region=US&placement=B06XT7M6P5&asins=B06XT7M6P5&linkId=1d7cca0b3f98a842618f4389cd09557f&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=0066c0&bg_color=ffffff">
      </iframe>
      <a target="_blank"  href="https://www.amazon.com/gp/offer-listing/B00OQVZDJM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B00OQVZDJM&linkCode=am2&tag=webboard05-20&linkId=11f9d65faa9df0cd9781916bcb13c639"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=B00OQVZDJM&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=webboard05-20" ></a><img src="//ir-na.amazon-adsystem.com/e/ir?t=webboard05-20&l=am2&o=1&a=B00OQVZDJM" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
    </div>
  </div>
  <div class="col-md-6 six">
    <div class="mid short">
      <div>
        <div class="cat-header">
          <%= @category.description %>
        </div>
        <% @posts_page.each do |post| %>
          <div class="cat-post detail">
            <%= render partial: 'likes/like', locals: { post: post } %>
            <%= link_to (post.body.html_safe).truncate(180), category_post_path(@category, post) %><br />
            <small>
              <div class="time-post">posted <%= time_ago_in_words(post.created_at) %> ago by <span class="email"><%= post.user.email %></span></div>
              <div class="comment-count"><%= pluralize(post.comments.count, "comment") %></div>
            </small>
          </div>
        <% end %>
        <div class="bottom-align-div">
          <%= paginate @posts_page %><%= page_entries_info @posts_page %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-2 two">
    <div class="right short middiv">
      <% if is_admin? %>
        <%= link_to "Edit Category", edit_category_path, class: 'btn btn-primary' %>
        <%= link_to "Delete Category", @category, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this category?' } %>
        <br />      
      <% end %>
      <% if user_signed_in? %>
        <br />
        <%= link_to "New Post", new_category_post_path(@category), class: 'btn btn-primary' %>
        <br /><br />
      <% end %>
      <div class="middiv">
        <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=14&l=ur1&category=homeaudiohometheater&banner=0HA6YVEW8QYDHQPTF882&f=ifr&linkID=8c42dc50467874db22860d04ef7a6138&t=webboard05-20&tracking_id=webboard05-20" width="160" height="600" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>      
      </div>
    </div>
  </div>
  <div class="col-md-1 one">
  </div>
</div>