config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      post :downgrade
    end
  end
  
  resources :categories do
    resources :posts, except: [:index] 
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    post '/like' => 'likes#like', as: :like
    post '/unlike' => 'likes#unlike', as: :unlike
  end

  get 'home/faq'
  get 'home/contact'
  root 'home#about'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>wändering</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin" rel="stylesheet">
  </head>
  <body>
    <div class="shrink">
      <div class="menu menu-height">
        <nav class="navbar navbar-standard menu-height">
          <div class="container-fluid">
            <div class="navbar-header blue">
              <%= link_to "wändering", root_path, :class=>"navbar-brand" %>
            </div>
            <ul class="nav navbar-nav">    
              <li><%= link_to "Category", categories_path %></li>
              <li><%= link_to "Faq", home_faq_path %></li>
              <li><%= link_to "Contact", home_contact_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right user-info blue">
              <% if user_signed_in? %>
                <% if current_user.standard? %>
                  <li>standard user</li>  
                <% elsif current_user.seller? %>
                  <li>seller</li>  
                <% elsif current_user.admin? %>
                  <li>admin</li>  
                <% end %>
                <li>&nbsp;signed in as:&nbsp;</li> 
                <strong><%= current_user.email.truncate(30) %></strong> |
                <%= link_to edit_user_registration_path do %>
      	          <i class="glyphicon glyphicon-user"></i>
                <% end %> - 
                <%= link_to destroy_user_session_path, method: :delete do %>
      	          <i class="glyphicon glyphicon-log-out"></i>&nbsp;&nbsp;Sign Out
                <% end %>
              <% else %>
                <%= link_to new_user_registration_path do %>
      	          <i class="glyphicon glyphicon-pencil"></i>&nbsp;&nbsp;Sign Up
                <% end %> -
                <%= link_to new_user_session_path do %>
      	          <i class="glyphicon glyphicon-log-in"></i>&nbsp;&nbsp;Sign In
                <% end %>
              <% end %>
            </ul>
          </div>
        </nav>
      </div> 
      <div class="container">
        <div id="show-flash">
          <small>
          <% if flash[:notice] %>
            <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:notice] %>
            </div>
          <% elsif flash[:alert] %>
            <div class="alert alert-warning">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:alert] %>
            </div>
          <% end %>
          </small>
        </div>
        <script type="text/javascript">
            $(document).ready(function(){
            setTimeout(function(){
            $('#show-flash').remove();
          }, 4000);
         })
        </script>
      </div>
      <div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>